### ISSUE TITLE
模型加载

### ISSUE THREAD

**Issue by WeiminLee** [niuzaisheng/ScreenAgent#4]
再请教一个问题，训练好的sat模型如何再两张GPU上加载并推理？ 我目前只有A100（40G）的版本，有时推理会报内u才能溢出。
请问如何设置多GPU推理？

下面模型加载部分如何设置呢？谢谢
`# load model
        model, model_args = AutoModel.from_pretrained(
            args.from_pretrained,
            args=argparse.Namespace(
                deepspeed=None,
                local_rank=0,
                rank=0,
                world_size=1,
                model_parallel_size=1,
                mode='inference',
                skip_init=True,
                use_gpu_initialization=True if torch.cuda.is_available() else False,
                device='cuda',
                overwrite_args={'model_parallel_size': 2},
                **vars(args)
            ))
        model.add_mixin('auto-regressive', CachedAutoregressiveMixin())
        self.model = model.eval()
`

**Comment by WeiminLee** [comment]
# load model
        model, model_args = AutoModel.from_pretrained(
            args.from_pretrained,
            args=argparse.Namespace(
                deepspeed=None,
                local_rank=0,
                rank=0,
                world_size=1,
                model_parallel_size=1,
                mode='inference',
                skip_init=True,
                use_gpu_initialization=True if torch.cuda.is_available() else False,
                device='cuda',
                overwrite_args={'model_parallel_size': 2},
                **vars(args)
            ))
        model.add_mixin('auto-regressive', CachedAutoregressiveMixin())
        self.model = model.eval()

**Comment by Remian777** [comment]
> 再请教一个问题，训练好的sat模型如何再两张GPU上加载并推理？ 我目前只有A100（40G）的版本，有时推理会报内u才能溢出。 请问如何设置多GPU推理？
> 
> 下面模型加载部分如何设置呢？谢谢 `# load model model, model_args = AutoModel.from_pretrained( args.from_pretrained, args=argparse.Namespace( deepspeed=None, local_rank=0, rank=0, world_size=1, model_parallel_size=1, mode='inference', skip_init=True, use_gpu_initialization=True if torch.cuda.is_available() else False, device='cuda', overwrite_args={'model_parallel_size': 2}, **vars(args) )) model.add_mixin('auto-regressive', CachedAutoregressiveMixin()) self.model = model.eval() `

你好，请问你这个问题解决了吗？

**Comment by ttq85** [comment]
> # load model
> ```
>     model, model_args = AutoModel.from_pretrained(
>         args.from_pretrained,
>         args=argparse.Namespace(
>             deepspeed=None,
>             local_rank=0,
>             rank=0,
>             world_size=1,
>             model_parallel_size=1,
>             mode='inference',
>             skip_init=True,
>             use_gpu_initialization=True if torch.cuda.is_available() else False,
>             device='cuda',
>             overwrite_args={'model_parallel_size': 2},
>             **vars(args)
>         ))
>     model.add_mixin('auto-regressive', CachedAutoregressiveMixin())
>     self.model = model.eval()
> ```

Not work for me, It seems only One GPU is used, although i have 2 GPU in one node.  and I keep get oom error as below, Any help? Thanks!


(py3-11) ubuntu@10-60-241-123:/home/ScreenAgent/ScreenAgent/train$ vi cogagent_model_worker.py
(py3-11) ubuntu@10-60-241-123:/home/ScreenAgent/ScreenAgent/train$ RANK=0 WORLD_SIZE=1 LOCAL_WORLD_SIZE=2  LOCAL_RANK=0 sudo  /home/ubuntu/miniconda3/envs/py3-11/bin/python   ./cogagent_model_worker.py --host 0.0.0.0  --port 40000 --from_pretrained "./saved_models/ScreenAgent-2312" --bf16 --max_length 2048
[2024-06-22 14:25:46,646] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.0), only 1.0.0 is known to be compatible
2024-06-22 14:25:48 | INFO | model_worker | args: Namespace(host='0.0.0.0', port=40000, max_length=2048, top_p=0.4, top_k=1, temperature=0.8, chinese=False, version='chat', quant=None, stream_chat=False, from_pretrained='./saved_models/ScreenAgent-2312', local_tokenizer='lmsys/vicuna-7b-v1.5', fp16=False, bf16=True)
[2024-06-22 14:25:48,488] [INFO] building FineTuneTrainCogAgentModel model ...
2024-06-22 14:25:48 | INFO | sat | building FineTuneTrainCogAgentModel model ...
[2024-06-22 14:25:48,490] [INFO] [RANK 0] > initializing model parallel with size 1
2024-06-22 14:25:48 | INFO | sat | [RANK 0] > initializing model parallel with size 1
[2024-06-22 14:25:48,491] [INFO] [RANK 0] You are using model-only mode.
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
2024-06-22 14:25:48 | INFO | sat | [RANK 0] You are using model-only mode.
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
2024-06-22 14:26:07 | ERROR | stderr | [rank0]: Traceback (most recent call last):
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:   File "/home/ScreenAgent/ScreenAgent/train/./cogagent_model_worker.py", line 146, in <module>
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:     worker = ModelWorker(args)
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:              ^^^^^^^^^^^^^^^^^
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:   File "/home/ScreenAgent/ScreenAgent/train/./cogagent_model_worker.py", line 41, in __init__
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:     model, model_args = FineTuneTrainCogAgentModel.from_pretrained(
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:   File "/home/ubuntu/miniconda3/envs/py3-11/lib/python3.11/site-packages/sat/model/base_model.py", line 207, in from_pretrained
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:     return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:   File "/home/ubuntu/miniconda3/envs/py3-11/lib/python3.11/site-packages/sat/model/base_model.py", line 199, in from_pretrained_base
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:     model = get_model(args, cls, **kwargs)
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:   File "/home/ubuntu/miniconda3/envs/py3-11/lib/python3.11/site-packages/sat/model/base_model.py", line 404, in get_model
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:     model = model_cls(args, params_dtype=params_dtype, **kwargs)
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:   File "/home/ScreenAgent/ScreenAgent/train/models/cogagent_model.py", line 196, in __init__
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:     super().__init__(args, transformer=transformer, parallel_output=parallel_output, **kw_args)
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:   File "/home/ScreenAgent/ScreenAgent/train/models/cogagent_model.py", line 157, in __init__
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:     self.add_mixin("eva", ImageMixin(args))
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:                           ^^^^^^^^^^^^^^^^
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:   File "/home/ScreenAgent/ScreenAgent/train/models/cogagent_model.py", line 110, in __init__
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:     self.vit_model = EVA2CLIPModel(EVA2CLIPModel.get_args(**vars(vit_args)))
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:   File "/home/ScreenAgent/ScreenAgent/train/models/eva_clip_model.py", line 110, in __init__
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:     super().__init__(args, transformer=transformer, parallel_output=parallel_output, **kwargs)
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:   File "/home/ubuntu/miniconda3/envs/py3-11/lib/python3.11/site-packages/sat/model/base_model.py", line 84, in __init__
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:     self.transformer = BaseTransformer(
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:                        ^^^^^^^^^^^^^^^^
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:   File "/home/ubuntu/miniconda3/envs/py3-11/lib/python3.11/site-packages/sat/model/transformer.py", line 514, in __init__
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:     [get_layer(layer_id) for layer_id in range(num_layers)])
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:   File "/home/ubuntu/miniconda3/envs/py3-11/lib/python3.11/site-packages/sat/model/transformer.py", line 514, in <listcomp>
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:     [get_layer(layer_id) for layer_id in range(num_layers)])
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:      ^^^^^^^^^^^^^^^^^^^
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:   File "/home/ubuntu/miniconda3/envs/py3-11/lib/python3.11/site-packages/sat/model/transformer.py", line 482, in get_layer
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:     return BaseTransformerLayer(
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:            ^^^^^^^^^^^^^^^^^^^^^
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:   File "/home/ubuntu/miniconda3/envs/py3-11/lib/python3.11/site-packages/sat/model/transformer.py", line 371, in __init__
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:     self.mlp = MLP(
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:                ^^^^
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:   File "/home/ubuntu/miniconda3/envs/py3-11/lib/python3.11/site-packages/sat/model/transformer.py", line 217, in __init__
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:     self.dense_h_to_4h = ColumnParallelLinear(
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:                          ^^^^^^^^^^^^^^^^^^^^^
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:   File "/home/ubuntu/miniconda3/envs/py3-11/lib/python3.11/site-packages/sat/mpu/layers.py", line 256, in __init__
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:     self.weight = Parameter(torch.empty(self.output_size_per_partition,
2024-06-22 14:26:07 | ERROR | stderr | [rank0]:                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-22 14:26:07 | ERROR | stderr | [rank0]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 106.00 MiB. GPU

**Comment by CA-TT-AC** [comment]
Same question, any solution? T.T

**Comment by ttq85** [comment]
I looked up the project cogoagent, it use torch run under the situation of  multiple GPU. the command is like this:

++++++++++++
/home/ubuntu/miniconda3/envs/py3-11/bin/torchrun --standalone --nnodes=1 --nproc-per-node=2 cogagent_model_worker.py --host 0.0.0.0  --port 8888 --from_pretrained "./saved_models/ScreenAgent-2312" --bf16 --max_length 2048 

++++++++

and cogagent_model_worker.py  is modified as below:
++++++
"""
A model worker executes the model.
"""
import argparse
import time
import uuid

from fastapi import FastAPI, Request
import torch
import uvicorn
from functools import partial

from PIL import Image
from io import BytesIO
import base64

from sat.model.mixins import CachedAutoregressiveMixin
from models.cogagent_model import FineTuneTrainCogAgentModel

from utils import chat, llama2_tokenizer, llama2_text_processor_inference, get_image_processor

from logger_util import build_logger

GB = 1 << 30

worker_id = str(uuid.uuid4())[:6]
logger = build_logger("model_worker", f"model_worker_{worker_id}.log")


def load_image_from_base64(image):
    return Image.open(BytesIO(base64.b64decode(image))).convert("RGB")


class ModelWorker:
    def __init__(self, args):

        args.stream_chat = False
        self.args = args
        import os
        os.environ["CUDA_VISIBLE_DEVICES"] = "0,1" 
        rank = int(os.environ.get('RANK', 0))

        # load model
        model, model_args = FineTuneTrainCogAgentModel.from_pretrained(
            args.from_pretrained,
            args=argparse.Namespace(
                deepspeed=None,
                local_rank=rank,
                rank=rank,
                world_size=1,
                model_parallel_size=1,
                mode='inference',
                skip_init=True,
                use_gpu_initialization=True if torch.cuda.is_available() else False,
                device ='cuda',
                **vars(args)
                ),overwrite_args={'model_parallel_size': 2} )
        model.add_mixin('auto-regressive', CachedAutoregressiveMixin())
        self.model = model.eval()

        self.tokenizer = llama2_tokenizer(args.local_tokenizer, signal_type=args.version)
        self.image_processor = get_image_processor(224)
        self.cross_image_processor = get_image_processor(1120)
        self.text_processor_infer = llama2_text_processor_inference(self.tokenizer, args.max_length, model.image_length)


    @torch.inference_mode()
    def direct_generate(self, params):
        print("into direct_generate")
        import os

        rank = int(os.environ.get('RANK', 0))
        if rank >= 0:

            prompt = params["prompt"]
            history = params.get("history", [])
            image_base64 = params.get("image", None)
            image_mode = params.get("image_mode", "copy") # copy or resize
            image_path = None
            if image_base64 is not None:
                image = load_image_from_base64(image_base64)

            max_size = (1120, 1120)
            if image_mode == "resize":
                scale = min(max_size[0] / image.size[0], max_size[1] / image.size[1])
                image = image.resize((int(image.size[0] * scale), int(image.size[1] * scale)), Image.BILINEAR)

            padded_image = Image.new("RGB", max_size, color="white")
            padded_image.paste(image, (0, 0))


        #torch.distributed.broadcast_object_list(image_path, 0)
        #torch.distributed.broadcast_object_list(prompt, 0)
        #torch.distributed.broadcast_object_list(history, 0)

        start_time = time.time()
        response, history, cache_image = chat(
            image_path,
            self.model,
            self.text_processor_infer,
            self.image_processor,
            prompt,
            history=history,
            cross_img_processor=self.cross_image_processor,
            image=image,
            max_length=args.max_length,
            top_p=args.top_p,
            temperature=args.temperature,
            top_k=args.top_k,
            invalid_slices=self.text_processor_infer.invalid_slices,
            args=args
        )
        duration = time.time() - start_time
        print("response", response)
        print("duration", duration)

        response = {
            "text": response,
            "duration": duration,
            "history": history,
            "error_code": 0
        }
        return response


app = FastAPI()

@app.post("/worker_generate")
async def generate(request: Request):
    params = await request.json()
    response_data = worker.direct_generate(params)
    return response_data

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", type=str, default="localhost")
    parser.add_argument("--port", type=int, default=21002)

    parser.add_argument("--max_length", type=int, default=2048, help='max length of the total sequence')
    parser.add_argument("--top_p", type=float, default=0.4, help='top p for nucleus sampling')
    parser.add_argument("--top_k", type=int, default=1, help='top k for top k sampling')
    parser.add_argument("--temperature", type=float, default=.8, help='temperature for sampling')
    parser.add_argument("--chinese", action='store_true', help='Chinese interface')
    parser.add_argument("--version", type=str, default="chat", choices=['chat', 'vqa', 'chat_old', 'base'], help='version of language process. if there is \"text_processor_version\" in model_config.json, this option will be overwritten')
    parser.add_argument("--quant", choices=[8, 4], type=int, default=None, help='quantization bits')

    parser.add_argument("--stream_chat", action='store_true', help='streaming chat')

    parser.add_argument("--from_pretrained", type=str, default="checkpoints/ScreenAgent-2312", help='pretrained ckpt')
    parser.add_argument("--local_tokenizer", type=str, default="lmsys/vicuna-7b-v1.5", help='tokenizer path')
    parser.add_argument("--fp16", action="store_true")
    parser.add_argument("--bf16", action="store_true")

    args = parser.parse_args()
    logger.info(f"args: {args}")

    worker = ModelWorker(args)
    import os
    try:
        rank = int(os.environ.get('RANK', 0))
        world_size = int(os.environ.get('WORLD_SIZE', 1))
        print(rank)
        print(world_size)
        if rank == 0:
            uvicorn.run(app, host=args.host, port=args.port, log_level="info")
        else:
            uvicorn.run(app, host=args.host, port=80, log_level="info")
    except Exception as ex:
        print(ex)


++++++
it worked for me.

**Comment by CA-TT-AC** [comment]
@ttq85 Thanks for your hint! I v tried your solution, but it is stuck after printing "into direct_generate". Have u ever meet this problem? My devices are 2*V100.

**Comment by ttq85** [comment]
> @ttq85 Thanks for your hint! I v tried your solution, but it is stuck after printing "into direct_generate" while inference. Have u ever meet this problem? My devices are 2*V100.

Sorry I don't have the  model env anymore. My device were  2*4090.  The model couldn't satisfy my requests, It seems Gpt4 works more stablely:(    But You can add some logs within the script and check it further
